"""Decision and economic candidate action models."""
from sqlalchemy import Column, String, Float, Integer, ForeignKey, JSON
from sqlalchemy.orm import relationship
from app.core.database import Base
from app.models.base import UUIDMixin, TimestampMixin


class DecisionRecord(Base, UUIDMixin, TimestampMixin):
    """
    Structured record of the final decision generated by the Decision Engine.
    """
    __tablename__ = "decisions"

    case_id = Column(String(36), ForeignKey("cases.id", ondelete="CASCADE"), nullable=False, index=True)

    decision = Column(String(50), nullable=False)  # ACT, WAIT, DONT_ACT, ESCALATE
    recommended_action = Column(String(50), nullable=True)  # RETRY, PAYMENT_LINK, REMINDER, ALTERNATE_METHOD, HUMAN_ESCALATION, NO_ACTION
    recommended_timing = Column(String(100), default="IMMEDIATE")  # IMMEDIATE, DELAY_1H, DELAY_4H, DELAY_24H, NEXT_QUIET_HOURS_END
    
    # ML Prediction Snapshot
    ml_model_name = Column(String(100), nullable=True)
    ml_model_version = Column(String(50), nullable=True)
    ml_confidence = Column(Float, nullable=True)
    natural_recovery_prob = Column(Float, nullable=False)
    
    # Economic Optimization Snapshot
    incremental_lift = Column(Float, nullable=True)
    expected_incremental_revenue = Column(Float, nullable=True)
    expected_action_cost = Column(Float, nullable=True)
    expected_incentive_cost = Column(Float, nullable=True)
    expected_friction_cost = Column(Float, nullable=True)
    expected_incremental_contribution = Column(Float, nullable=True)
    
    # Policy Status
    policy_status = Column(String(50), default="APPROVED")  # APPROVED, VETOED, SUPPRESSED, ESCALATED
    policy_reason = Column(String(500), nullable=True)
    
    # Human-readable explanation
    decision_reason = Column(String(1000), nullable=False)
    explanation_breakdown = Column(JSON, nullable=True)

    # Relationships
    case = relationship("Case", back_populates="decisions")
    candidate_actions = relationship("CandidateActionEvaluation", back_populates="decision_record", cascade="all, delete-orphan")


class CandidateActionEvaluation(Base, UUIDMixin, TimestampMixin):
    """
    Economic evaluation breakdown for every candidate action evaluated for a case.
    Enables explainable Decision Explorer matrices.
    """
    __tablename__ = "candidate_action_evaluations"

    decision_id = Column(String(36), ForeignKey("decisions.id", ondelete="CASCADE"), nullable=False, index=True)
    case_id = Column(String(36), index=True, nullable=False)

    action_type = Column(String(50), nullable=False)  # RETRY, PAYMENT_LINK, REMINDER, ALTERNATE_METHOD, HUMAN_ESCALATION, NO_ACTION
    
    # Probabilities
    natural_recovery_prob = Column(Float, nullable=False)
    action_recovery_prob = Column(Float, nullable=False)
    incremental_lift = Column(Float, nullable=False)  # action_recovery_prob - natural_recovery_prob
    
    # Financials (INR)
    payment_amount = Column(Float, nullable=False)
    expected_recovery_value = Column(Float, nullable=False)  # action_recovery_prob * payment_amount
    expected_incremental_revenue = Column(Float, nullable=False)  # incremental_lift * payment_amount
    
    # Costs (INR)
    action_cost = Column(Float, default=0.0)      # e.g. gateway fees, SMS fees
    incentive_cost = Column(Float, default=0.0)   # discounts, waivers
    friction_cost = Column(Float, default=0.0)    # customer fatigue cost
    total_cost = Column(Float, default=0.0)
    
    # Net Incremental Contribution (INR)
    expected_incremental_contribution = Column(Float, nullable=False)
    
    # Policy approval for this specific action
    policy_allowed = Column(Integer, default=1)  # 1 = allowed, 0 = blocked
    policy_block_reason = Column(String(255), nullable=True)
    
    rank = Column(Integer, default=1)  # 1 = best valid action
    is_selected = Column(Integer, default=0)

    # Relationship
    decision_record = relationship("DecisionRecord", back_populates="candidate_actions")
